config/routes.rb
RiskAssessDemo::Application.routes.draw do
  root :to => "home#index"

  resources :departments do
    collection do
        get "data"
        get "view"
        get "dbaction"
      end
    resources :tasks do
      resources :hazards 
    end
  end

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :department
  has_many :hazards, :dependent => :destroy
  attr_accessible :complete,
  				  :date_completed, 
  				  :description,
  				  :hazard1,
  				  :hazard2,
  				  :hazard3,
  				  :hazard4,
  				  :hazard5,
  				  :hazard6,
  				  :hazard7,
  				  :hazard8,
  				  :hazard9,
  				  :hazard10,
  				  :hazard11,
  				  :hazard12,
  				  :hazard13,
  				  :hazard14,
  				  :hazard15,
  				  :hazard16,
  				  :hazard17,
  				  :hazard18,
  				  :hazard19,
  				  :hazard20,
  				  :location,
            :team,
            :shifttime,
            :shiftday,
            :shiftnight,
            :shiftweekend,
            :shiftwrker,
            :equipmachine,
            :machine,
            :equiptool,
            :tool,
            :equipdevice,
            :device,
            :restricted,
            :restrictmethod1,
            :restrictmethod2,
            :restrictmethod3,
            :history,
  				  :name,
            :envhaz1,
            :envhaz2,
            :envhaz3,
            :envhaz4,
            :envhaz5,
            :envhaz6,
            :envhaz7,
            :envhaz8
  accepts_nested_attributes_for :hazards
  attr_accessible :hazards_attributes
  #accepts_nested_attributes_for :hazards, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  before_filter :get_department
  before_filter :logged_in?
  def get_department
    @department=Department.find(params[:department_id])
  end
  def index
    @tasks = @department.tasks.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = @department.tasks.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = @department.tasks.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: [@department,@task] }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = @department.tasks.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = @department.tasks.new(params[:task])
    @task.hazards.build
    respond_to do |format|
      if @task.save
        format.html { redirect_to [@department,@task], notice: 'Task was successfully created.' }
        format.json { render json: @department, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = @department.tasks.find(params[:id])
    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to [@department,@task], notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = @department.tasks.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for([@department,@task])  do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- task description form table contains editable fields for:
		- Task Name
		- Task Description
		- Task Location
		- Hazards Associated with Task
		- Assessment Completed
		- Date Completed -->
	<div class="table">
		<table>
			<tr>
				<th class="top" colspan="2">
					Task Description
				</th>
			</tr>
			<tr>
				<td class="tleft w20">
					Task Name:
				</td>
				<td class="tleft">
					<%= f.text_field :name, :class=>"field w99" %>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Task Description:
				</td>
				<td class="tleft">
					<%= f.text_area :description, :class=>"area w99" %>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Task Location:
				</td>
				<td class="tleft">
					<%= f.text_field :location, :class=>"field w99" %>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Review Team:
				</td>
				<td class="tleft">
					<%= f.text_area :team, :class=>"field w99" %>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Work Shift:
				</td>
				<td>
					<table class="w100">
						<tr>
							<td class="tleft w30">
								Shift Length (select one):
							</td>
							<td class="tcenter">
								<ul class="menu w100">
									<li class="checkbox2"><%= f.radio_button :shifttime, 'Part-Time' %><%=f.label :shifttime, 'Part-Time' %></li>
									<li class="checkbox2"><%= f.radio_button :shifttime, 'Full-Time' %><%=f.label :shifttime, 'Full-Time' %></li>
								</ul>
							</td>
						</tr>
						<tr>
							<td class="tleft w30">
								Shift Time (select all that apply):
							</td>
							<td class="tcenter">
								<ul class="menu w100">
									<li class="checkbox3"><%= f.check_box :shiftday, :class=>"box" %><%= f.label :shiftday, '  Daytime', :class=>"label" %></li>
									<li class="checkbox3"><%= f.check_box :shiftnight, :class=>"box" %><%= f.label :shiftnight, '  Nighttime', :class=>"label" %></li>
									<li class="checkbox3"><%= f.check_box :shiftweekend, :class=>"box" %><%= f.label :shiftweekend, '  Weekend', :class=>"label" %></li>
								</ul>
							</td>
						</tr>
						<tr>
							<td class="tleft w30">
								Type of Work (select one):
							</td>
							<td class="tcenter">
								<ul class="menu w100">
									<li class="checkbox2"><%= f.radio_button :shiftwrker, 'Lone-Worker' %><%=f.label :shiftwrker, 'Lone-Worker' %></li>
									<li class="checkbox2"><%= f.radio_button :shiftwrker, 'Group/Team' %><%=f.label :shiftwrker, 'Group/Team' %></li>
								</ul>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Equipment Used:
				</td>
				<td>
					<table class="w100">
						<tr>
							<td class="tleft w30">
								<ul class="menu w100">
									<li class="checkbox1"><%= f.check_box :equipmachine, :class=>"box" %><%= f.label :equipmachine, '  Machine(s)', :class=>"label" %></li>
								</ul>
							</td>
							<td class="tleft w10">
								Description:
							</td>
							<td>
								<%= f.text_area :machine, :class=>"field w99" %>
							</td>
						</tr>
						<tr>
							<td class="tleft w30">
								<ul class="menu w100">
									<li class="checkbox1"><%= f.check_box :equiptool, :class=>"box" %><%= f.label :equiptool, '  Tool(s)', :class=>"label" %></li>
								</ul>
							</td>
							<td class="tleft w10">
								Description:
							</td>
							<td>
								<%= f.text_area :tool, :class=>"field w99" %>
							</td>
						</tr>
						<tr>
							<td class="tleft w30">
								<ul class="menu w100">
									<li class="checkbox1"><%= f.check_box :equipdevice, :class=>"box" %><%= f.label :equipdevice, '  Other Device(s)', :class=>"label" %></li>
								</ul>
							</td>
							<td class="tleft w10">
								Description:
							</td>
							<td>
								<%= f.text_area :device, :class=>"field w99" %>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Restricted Access:
				</td>
				<td>
					<table class="w100">
						<tr>
							<td class="tleft w30">
								Restricted Area (select one):
							</td>
							<td class="tcenter">
								<ul class="menu w100">
									<li class="checkbox2"><%= f.radio_button :restricted, 'True' %><%=f.label :restricted, 'Yes' %></li>
									<li class="checkbox2"><%= f.radio_button :restricted, 'False' %><%=f.label :restricted, 'No' %></li>
								</ul>
							</td>
						</tr>
						<tr>
							<td class="tleft w30">
								Restriction Method (select all that apply):
							</td>
							<td class="tcenter">
								<ul class="menu w100">
									<li class="checkbox3"><%= f.check_box :restrictmethod1, :class=>"box" %><%= f.label :restrictmethod1, '  Badge', :class=>"label" %></li>
									<li class="checkbox3"><%= f.check_box :restrictmethod2, :class=>"box" %><%= f.label :restrictmethod2, '  Key', :class=>"label" %></li>
									<li class="checkbox3"><%= f.check_box :restrictmethod3, :class=>"box" %><%= f.label :restrictmethod3, '  Other', :class=>"label" %></li>
								</ul>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Accident History:
				</td>
				<td>
					<%= f.text_area :history, :class=>"field w99" %>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Hazards Associated </br> with this Task:
				</td>
				<td class="tcenter">
					<ul class="menu w100">
						<li class="checkbox4"><%= f.label :hazard1, 'Access & Egress', :class=>"label" %></br><%= f.check_box :hazard1, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :hazard2, 'Biohazard', :class=>"label" %></br><%= f.check_box :hazard2, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :hazard3, 'Co-Worker', :class=>"label" %></br><%= f.check_box :hazard3, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :hazard4, 'Cut & Puncture', :class=>"label" %></br><%= f.check_box :hazard4, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :hazard5, 'Ergonomics', :class=>"label" %></br><%= f.check_box :hazard5, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :hazard6, 'Slip, Trip or Fall', :class=>"label" %></br><%= f.check_box :hazard6, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :hazard7, 'Fire', :class=>"label" %></br><%= f.check_box :hazard7, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :hazard8, 'Hazardous Atmosphere', :class=>"label" %></br><%= f.check_box :hazard8, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :hazard9, 'Hazardous Energy', :class=>"label" %></br><%= f.check_box :hazard9, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :hazard10, 'Hazardous Materials', :class=>"label" %></br><%= f.check_box :hazard10, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :hazard11, 'Lasers', :class=>"label" %></br><%= f.check_box :hazard11, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :hazard12, 'Lone-Worker', :class=>"label" %></br><%= f.check_box :hazard12, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :hazard13, 'Magnetism', :class=>"label" %></br><%= f.check_box :hazard13, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :hazard14, 'Mechanical Handling', :class=>"label" %></br><%= f.check_box :hazard14, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :hazard15, 'Noise, Vibration & Light', :class=>"label" %></br><%= f.check_box :hazard15, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :hazard16, 'Overhead', :class=>"label" %></br><%= f.check_box :hazard16, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :hazard17, 'Radiation', :class=>"label" %></br><%= f.check_box :hazard17, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :hazard18, 'Road', :class=>"label" %></br><%= f.check_box :hazard18, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :hazard19, 'Temperature', :class=>"label" %></br><%= f.check_box :hazard19, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :hazard20, 'Tool/Machinery', :class=>"label" %></br><%= f.check_box :hazard20, :class=>"box" %></li>
					</ul>
				</td>
			</tr>
		<!-- Fields for Environmental Hazards that don't have associated forms -->
			<tr>
				<td class="tleft">
					Environmental Hazards Associated </br> with this Task:
				</td>
				<td class="tcenter">
					<ul class="menu w100">
						<li class="checkbox4"><%= f.label :envhaz1, 'Air Emissions', :class=>"label" %></br><%= f.check_box :envhaz1, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :envhaz2, 'Water Discharge', :class=>"label" %></br><%= f.check_box :envhaz2, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :envhaz3, 'Waste Generation', :class=>"label" %></br><%= f.check_box :envhaz3, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :envhaz4, 'Land Discharge', :class=>"label" %></br><%= f.check_box :envhaz4, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :envhaz5, 'Raw Material Use', :class=>"label" %></br><%= f.check_box :envhaz5, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :envhaz6, 'Energy Use', :class=>"label" %></br><%= f.check_box :envhaz6, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :envhaz7, 'Energy Release', :class=>"label" %></br><%= f.check_box :envhaz7, :class=>"box" %></li>
						<li class="checkbox4"><%= f.label :envhaz8, 'Nuisance', :class=>"label" %></br><%= f.check_box :envhaz8, :class=>"box" %></li>
					</ul>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Assessment Complete:
				</td>
				<td class="tleft">
					<%= f.check_box :complete %>
					<%= f.label :complete, " (Select Check Box if Department Assessment is Complete)"%>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Date Completed:
				</td>
				<td class="tleft">
					<%= f.date_select :date_completed %>
					<%= f.label :date_completed, " (Select Date on which Assessment was Completed)" %>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Task Actions:
				</td>
				<!-- task description table contains task information (above) and action buttons -->
				<td class="tcenter">
					<ul class="menu w100">
						<li><%= f.submit 'Save Task Info', :class=>"link2" %></li>
						<li><%= link_to 'Back to Task List', department_path(@department), :class=>"link2" %></li>
					</ul>
				</td>
			</tr>
		</table>
	</div>
<% end %>

app/views/tasks/_index.html.erb
<!-- the entire task index table is contained in div w/ class="table" -->
<div class="table">
	<!-- first subtable contains the main header and the column headers -->
	<table>
		<tr>
			<th class="top" colspan="4">
				Tasks Performed in <%= @department.name %> Department
			</th>
		</tr>
		<tr>
			<th class="sub tleft w25">
				Task Name:
			</th>
			<th class="sub tleft w25">
				Task Location:
			</th>
			<th class="sub tcenter w20">
				Date Complete:
			</th>
			<th class="sub tcenter">
				Task Actions:
			</th>
		</tr>
	</table>
	<!-- div_for creates new subtable for each task created -->
	<%= div_for(@department.tasks) do |task| %>
		<!-- each task subtable contains task information and action buttons -->
		<table>
			<tr>
				<td class="tleft w25">
					<%= task.name %>
				</td>
				<td class="tleft w25">
					<%= task.location %>
				</td>
				<td class="tcenter w20">
					<%= task.date_completed %>
				</td>
				<td class="tcenter">
					<ul class="menu w100">
						<li><%= link_to 'Edit Info', edit_department_task_path(@department,task), :class=>"link3" %></li>
						<li><%= link_to 'Edit Hazards', department_task_path(@department,task), :class=>"link3" %></li>
						<li><%= link_to 'Destroy', [@department,task], method: :delete, remote: true, data: { confirm: 'Are you sure?' }, :class=>"link3" %></li>
					</ul>
				</td>
			</tr>
		</table>
	<% end %>
	<!-- last subtable contains the button to create new tasks -->
	<table>
		<tr>
			<td class="tcenter" colspan="4">
				<%= link_to 'Create New Task', new_department_task_path(@department), :class=>"link1" %>
			</td>
		</tr>
	</table>
</div>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/show.html.erb
<!-- Reference print stylesheet -->
<%= stylesheet_link_tag 'print', :media => 'print'%>
<!-- the entire task description table is contained in div w/ class="table" -->
<div class="table">
	<table>
		<tr>
			<th class="top" colspan="2">
				<%= @task.name %> Task Description
			</th>
		</tr>
		<tr>
			<th class="sub tleft w20">
				Task Name:
			</th>
			<th class="sub tleft">
				<%= @task.name %>
			</th>
		</tr>
		<tr>
			<td class="tleft">
				Task Description:
			</td>
			<td class="tleft">
				<%= @task.description %>
			</td>
		</tr>
		<tr>
			<td class="tleft">
				Task Location:
			</td>
			<td class="tleft">
				<%= @task.location %>
			</td>
		</tr>
		<tr>
			<td class="tleft">
				Assessment Complete:
			</td>
			<td class="tleft">
				<%= @task.complete ? 'Yes' : 'No' %>
			</td>
		</tr>
		<tr>
			<td class="tleft">
				Date Completed:
			</td>
			<td class="tleft">
				<%= @task.date_completed %>
			</td>
		</tr>
		<tr>
			<td class="tleft">
				Task Actions:
			</td>
			<!-- task description table contains task information (above) and action buttons -->
			<td class="tcenter">
				<ul class="menu w100">
					<li><%= link_to 'Edit Task Info', edit_department_task_path(@department,@task), :class=>"link2" %></li>
					<li><%= link_to 'Back to Task List', department_path(@department), :class=>"link2" %></li>
				</ul>
			</td>
		</tr>
	</table>
	<table>
		<tr>
			<th class="sub tleft w20" colspan="2">
				<!-- blank row to distinguish task description from hazards descriptions -->
			</th>
		</tr>
		<!-- hazard list - linked via task javascript to populate based on items checked in task form -->
		<tr>
			<td class="tcenter w20 sidebarprint">
				<ul class="menu w100">
					<li class="checkbox1 one hidden yes_no">
						<div class="hidden" id="index">1</div>
						<div class="label" id="haz1">Access & Egress</div>
						<div class="hidden" id="value"><%= @task.hazard1 ? '1' : '0' %></div>
						<div class="hidden" id="comma">,</div>
					</li>
					<li class="checkbox1 two hidden yes_no">
						<div class="hidden" id="index">2</div>
						<div class="label" id="haz2">Biohazard</div>
						<div class="hidden" id="value"><%= @task.hazard2 ? '1' : '0' %></div>
						<div class="hidden" id="comma">,</div>
					</li>
					<li class="checkbox1 three hidden yes_no">
						<div class="hidden" id="index">3</div>
						<div class="label" id="haz3">Co-Worker</div>
						<div class="hidden" id="value"><%= @task.hazard3 ? '1' : '0' %></div>
						<div class="hidden" id="comma">,</div>
					</li>
					<li class="checkbox1 four hidden yes_no">
						<div class="hidden" id="index">4</div>
						<div class="label" id="haz4">Cut & Puncture</div>
						<div class="hidden" id="value"><%= @task.hazard4 ? '1' : '0' %></div>
						<div class="hidden" id="comma">,</div>
					</li>
					<li class="checkbox1 five hidden yes_no">
						<div class="hidden" id="index">5</div>
						<div class="label" id="haz5">Ergonomics</div>
						<div class="hidden" id="value"><%= @task.hazard5 ? '1' : '0' %></div>
						<div class="hidden" id="comma">,</div>
					</li>
					<li class="checkbox1 six hidden yes_no">
						<div class="hidden" id="index">6</div>
						<div class="label" id="haz6">Slip / Fall</div>
						<div class="hidden" id="value"><%= @task.hazard6 ? '1' : '0' %></div>
						<div class="hidden" id="comma">,</div>
					</li>
					<li class="checkbox1 seven hidden yes_no">
						<div class="hidden" id="index">7</div>
						<div class="label" id="haz7">Fire</div>
						<div class="hidden" id="value"><%= @task.hazard7 ? '1' : '0' %></div>
						<div class="hidden" id="comma">,</div>
					</li>
					<li class="checkbox1 eight hidden yes_no">
						<div class="hidden" id="index">8</div>
						<div class="label" id="haz8">Hazardous Atmosphere</div>
						<div class="hidden" id="value"><%= @task.hazard8 ? '1' : '0' %></div>
						<div class="hidden" id="comma">,</div>
					</li>
					<li class="checkbox1 nine hidden yes_no">
						<div class="hidden" id="index">9</div>
						<div class="label" id="haz9">Hazardous Energy</div>
						<div class="hidden" id="value"><%= @task.hazard9 ? '1' : '0' %></div>
						<div class="hidden" id="comma">,</div>
					</li>
					<li class="checkbox1 ten hidden yes_no">
						<div class="hidden" id="index">10</div>
						<div class="label" id="haz10">Hazardous Materials</div>
						<div class="hidden" id="value"><%= @task.hazard10 ? '1' : '0' %></div>
						<div class="hidden" id="comma">,</div>
					</li>
					<li class="checkbox1 eleven hidden yes_no">
						<div class="hidden" id="index">11</div>
						<div class="label" id="haz11">Lasers</div>
						<div class="hidden" id="value"><%= @task.hazard11 ? '1' : '0' %></div>
						<div class="hidden" id="comma">,</div>
					</li>
					<li class="checkbox1 twelve hidden yes_no">
						<div class="hidden" id="index">12</div>
						<div class="label" id="haz12">Lone-Worker</div>
						<div class="hidden" id="value"><%= @task.hazard12 ? '1' : '0' %></div>
						<div class="hidden" id="comma">,</div>
					</li>
					<li class="checkbox1 thirteen hidden yes_no">
						<div class="hidden" id="index">13</div>
						<div class="label" id="haz13">Magnetism</div>
						<div class="hidden" id="value"><%= @task.hazard13 ? '1' : '0' %></div>
						<div class="hidden" id="comma">,</div>
					</li>
					<li class="checkbox1 fourteen hidden yes_no">
						<div class="hidden" id="index">14</div>
						<div class="label" id="haz14">Mechanical Handling</div>
						<div class="hidden" id="value"><%= @task.hazard14 ? '1' : '0' %></div>
						<div class="hidden" id="comma">,</div>
					</li>
					<li class="checkbox1 fifteen hidden yes_no">
						<div class="hidden" id="index">15</div>
						<div class="label" id="haz15">Noise, Vibration & Light</div>
						<div class="hidden" id="value"><%= @task.hazard15 ? '1' : '0' %></div>
						<div class="hidden" id="comma">,</div>
					</li>
					<li class="checkbox1 sixteen hidden yes_no">
						<div class="hidden" id="index">16</div>
						<div class="label" id="haz16">Overhead</div>
						<div class="hidden" id="value"><%= @task.hazard16 ? '1' : '0' %></div>
						<div class="hidden" id="comma">,</div>
					</li>
					<li class="checkbox1 seventeen hidden yes_no">
						<div class="hidden" id="index">17</div>
						<div class="label" id="haz17">Radiation</div>
						<div class="hidden" id="value"><%= @task.hazard17 ? '1' : '0' %></div>
						<div class="hidden" id="comma">,</div>
					</li>
					<li class="checkbox1 eighteen hidden yes_no">
						<div class="hidden" id="index">18</div>
						<div class="label" id="haz18">Road</div>
						<div class="hidden" id="value"><%= @task.hazard18 ? '1' : '0' %></div>
						<div class="hidden" id="comma">,</div>
					</li>
					<li class="checkbox1 nineteen hidden yes_no">
						<div class="hidden" id="index">19</div>
						<div class="label" id="haz19">Temperature</div>
						<div class="hidden" id="value"><%= @task.hazard19 ? '1' : '0' %></div>
						<div class="hidden" id="comma">,</div>
					</li>
					<li class="checkbox1 twenty hidden yes_no">
						<div class="hidden" id="index">20</div>
						<div class="label" id="haz20">Tool/Machinery</div>
						<div class="hidden" id="value"><%= @task.hazard20 ? '1' : '0' %></div>
						<!-- NOTE: no comma div in last checkbox in hazard list -->
					</li>
				</ul>
			</td>
			<!-- hazard form generator - linked to task javascript to populate based on active checkbox selected -->
			<td>
				<%= form_for([@department,@task]) do |f| %>
				<div class="hidden">
					<%= f.label :complete, "Risk Assessment Complete"%>
					<%= f.check_box :complete %>
				</div>
				<table class="form">
					<tr>
						<td class="tcenter">
							<%= f.fields_for :hazards do |builder| %>
								<% if @task.hazard1 == true %>
									<%= render "access_fields", :f => builder %>
								<% end %>
								<% if @task.hazard2 == true %>
									<%= render "biohaz_fields", :f => builder %>
								<% end %>
								<% if @task.hazard3 == true %>
									<%= render "cowrk_fields", :f => builder %>
								<% end %>
								<% if @task.hazard4 == true %>
									<%= render "cut_fields", :f => builder %>
								<% end %>
								<% if @task.hazard5 == true %>
									<%= render "ergo_fields", :f => builder %>
								<% end %>
								<% if @task.hazard6 == true %>
									<%= render "fall_fields", :f => builder %>
								<% end %>
								<% if @task.hazard7 == true %>
									<%= render "fire_fields", :f => builder %>
								<% end %>
								<% if @task.hazard8 == true %>
									<%= render "hazatm_fields", :f => builder %>
								<% end %>
								<% if @task.hazard9 == true %>
									<%= render "hazengy_fields", :f => builder %>
								<% end %>
								<% if @task.hazard10 == true %>
									<%= render "hazmat_fields", :f => builder %>
								<% end %>
								<% if @task.hazard11 == true %>
									<%= render "laz_fields", :f => builder %>
								<% end %>
								<% if @task.hazard12 == true %>
									<%= render "lonewrk_fields", :f => builder %>
								<% end %>
								<% if @task.hazard13 == true %>
									<%= render "mag_fields", :f => builder %>
								<% end %>
								<% if @task.hazard14 == true %>
									<%= render "mechand_fields", :f => builder %>
								<% end %>
								<% if @task.hazard15 == true %>
									<%= render "noise_fields", :f => builder %>
								<% end %>
								<% if @task.hazard16 == true %>
									<%= render "ovrhead_fields", :f => builder %>
								<% end %>
								<% if @task.hazard17 == true %>
									<%= render "rad_fields", :f => builder %>
								<% end %>
								<% if @task.hazard18 == true %>
									<%= render "road_fields", :f => builder %>
								<% end %>
								<% if @task.hazard19 == true %>
									<%= render "temp_fields", :f => builder %>
								<% end %>
								<% if @task.hazard20 == true %>
									<%= render "tool_fields", :f => builder %>
								<% end %>
							<% end %>
						</td>
					</tr>
					<tr>
						<td class="tcenter">
							<ul class="menu w100">
								<li class="complete"><%= f.submit 'Save as Complete', :class=>"link2" %></li>
								<li><%= f.submit 'Save as Draft', :class =>"link2" %></li>
							</ul>
						</td>
					</tr>
				<% end %>
			</table>
			</td>
	</table>
</div>