config/routes.rb
RiskAssessDemo::Application.routes.draw do
  root :to => "home#index"

  resources :departments do
    collection do
        get "data"
        get "view"
        get "dbaction"
      end
    resources :tasks do
      resources :hazards 
    end
  end

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions

end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :tasks, :dependent => :destroy
  attr_accessible :complete, :date_completed, :description, :location, :name
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  # GET /departments
  # GET /departments.json
  before_filter :logged_in?
  def index
    @departments = Department.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @departments }
    end
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
    @department = Department.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/new
  # GET /departments/new.json
  def new
    @department = Department.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @department }
    end
  end

  # GET /departments/1/edit
  def edit
    @department = Department.find(params[:id])
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(params[:department])

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render json: @department, status: :created, location: @department }
      else
        format.html { render action: "new" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /departments/1
  # PUT /departments/1.json
  def update
    @department = Department.find(params[:id])

    respond_to do |format|
      if @department.update_attributes(params[:department])
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department = Department.find(params[:id])
    @department.destroy

    respond_to do |format|
      format.js
    end
  end
  def view
    render :layout => false
  end
  def data
    @departments = Department.all
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<%= form_for(@department) do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% @department.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<!-- department description form table contains editable fields for:
		- Department Name
		- Department Description
		- Department Location
		- Assessment Completed
		- Date Completed -->
	<div class="table">
		<table>
			<tr>
				<th class="top" colspan="2">
					Department Description
				</th>
			</tr>
			<tr>
				<td class="tleft w20">
					Department Name:
				</td>
				<td class="tleft">
					<%= f.text_field :name, :class=>"field w99" %>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Department Description:
				</td>
				<td class="tleft">
					<%= f.text_area :description, :class=>"area w99" %>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Department Location:
				</td>
				<td class="tleft">
					<%= f.text_field :location, :class=>"field w99" %>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Assessment Complete:
				</td>
				<td class="tleft">
					<%= f.check_box :complete %>
					<%= f.label :complete, " (Select Check Box if Department Assessment is Complete)"%>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Date Completed:
				</td>
				<td class="tleft">
					<%= f.date_select :date_completed %>
					<%= f.label :date_completed, " (Select Date on which Assessment was Completed)" %>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Department Actions:
				</td>
				<!-- department description table contains department information (above) and action buttons -->
				<td class="tcenter">
					<ul class="menu w100">
						<li><%= f.submit 'Save Department Info', :class=>"link2" %></li>
						<li><%= link_to 'Back to Department List', departments_path, :class=>"link2" %></li>
					</ul>
				</td>
			</tr>
		</table>
	</div>

<% end %>

app/views/departments/destroy.js.erb
$('#<%= dom_id(@department)%>').fadeOut();

app/views/departments/edit.html.erb
<%= render 'form' %>

app/views/departments/index.html.erb
<!-- the entire department index table is contained in div w/ class="table" -->
<div class="table">
	<!-- first subtable contains the main header and the column headers -->
	<table>
		<tr>
			<th class="top" colspan="4">
				Ipsen Department Listing
			</th>
		</tr>
		<tr>
			<th class="sub tleft w25">
				Department Name:
			</th>
			<th class="sub tleft w25">
				Department Location:
			</th>
			<th class="sub tcenter w20">
				Date Complete:
			</th>
			<th class="sub tcenter">
				Department Actions:
			</th>
		</tr>
	</table>
	<!-- div_for creates new subtable for each department created -->
	<%= div_for(@departments) do |department| %>
		<!-- each department subtable contains department information and action buttons -->
		<table>
			<tr>
				<td class="tleft w25">
					<%= department.name %>
				</td>
				<td class="tleft w25">
					<%= department.location %>
				</td>
				<td class="tcenter w20">
					<%= department.date_completed %>
				</td>
				<td class="tcenter">
					<ul class="menu w100">
						<li><%= link_to 'Edit Info', edit_department_path(department), :class=>"link3" %></li>
						<li><%= link_to 'Edit Tasks', department_path(department), :class=>"link3" %></li>
						<li><%= link_to 'Destroy', department, method: :delete, remote: true, data: { confirm: 'Are you sure?' }, :class=>"link3" %></li>
					</ul>
				</td>
			</tr>
		</table>
	<% end %>
	<!-- last subtable contains the button to create new departments -->
	<table>
		<tr>
			<td class="tcenter" colspan="4">
				<%= link_to 'Create New Department', new_department_path, :class=>"link1" %>
			</td>
		</tr>
	</table>
</div>

app/views/departments/show.html.erb
<!-- the entire department description table is contained in div w/ class="table" -->
<div class="table">
	<table>
		<tr>
			<th class="top" colspan="2">
				<%= @department.name %> Department Description
			</th>
		</tr>
		<tr>
			<th class="sub tleft w20">
				Department Name:
			</th>
			<th class="sub tleft">
				<%= @department.name %>
			</th>
		</tr>
		<tr>
			<td class="tleft">
				Department Description:
			</td>
			<td class="tleft">
				<%= @department.description %>
			</td>
		</tr>
		<tr>
			<td class="tleft">
				Department Location:
			</td>
			<td class="tleft">
				<%= @department.location %>
			</td>
		</tr>
		<tr>
			<td class="tleft">
				Assessment Complete:
			</td>
			<td class="tleft">
				<%= @department.complete ? 'Yes' : 'No' %>
			</td>
		</tr>
		<tr>
			<td class="tleft">
				Date Completed:
			</td>
			<td class="tleft">
				<%= @department.date_completed %>
			</td>
		</tr>
		<tr>
			<td class="tleft">
				Department Actions:
			</td>
			<!-- department description table contains department information (above) and action buttons -->
			<td class="tcenter">
				<ul class="menu w100">
					<li><%= link_to 'Edit Department Info', edit_department_path(@department), :class=>"link2" %></li>
					<li><%= link_to 'Back to Department List', departments_path, :class=>"link2" %></li>
				</ul>
			</td>
		</tr>
	</table>
</div>

<!-- show the list of all tasks associated with this department -->
<%= render 'tasks/index' %>

app/views/departments/view.html.erb
<html>
<head>
  <%= javascript_include_tag 'dhtmlx/dhtmlxcommon.js' %>
  <%= javascript_include_tag 'dhtmlx/dhtmlxgrid.js' %>
  <%= javascript_include_tag 'dhtmlx/dhtmlxgridcell.js' %>
  <%= javascript_include_tag 'dhtmlx/dhtmlxdataprocessor.js' %>
  <%= javascript_include_tag 'dhtmlx/ext/dhtmlxgrid_filter.js' %>
  <%= javascript_include_tag 'dhtmlx/ext/dhtmlxgrid_export.js' %>
  <%= stylesheet_link_tag 'dhtmlx/dhtmlxgrid.css' %>
  <%= stylesheet_link_tag 'dhtmlx/skins/dhtmlxgrid_dhx_skyblue.css' %>
</head>
<ul class="menu w100">
  <li><%= link_to 'Home', root_path, :class=>"link2" %></li>
  <li><%= link_to 'Departments', departments_path, :class=>"link2" %></li>
</ul>
<div id="grid_here" style="width:100%; height:600px;">
</div>
<script type="text/javascript" charset="utf-8">
    var grid = new dhtmlXGridObject("grid_here");
    grid.setImagePath("/images/dhtmlx/imgs");
    grid.setHeader("Department Name, Task Name, Access & Egress, Biohazard, Co-Worker, Cut & Puncture, Ergonomics, Slip Trip & Fall, Fire & Explosion, Hazardous Atmosphere, Hazardous Energy, Hazardous Materials, Laser, Lone Worker, Magnetic Field, Mechanical Handling, Noise Vibration & Light, Overhead, Radiation, Road, Temperature, Tool/Machinery, Air Emissions, Water Discharge, Waste Generation, Land Discharge, Raw Material Use, Energy Use, Energy Release, Nuisance");
    grid.setColSorting("str,str,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int");
    grid.attachHeader("#text_filter,#text_filter,#numeric_filter,#numeric_filter,#numeric_filter,#numeric_filter,#numeric_filter,#numeric_filter,#numeric_filter,#numeric_filter,#numeric_filter,#numeric_filter,#numeric_filter,#numeric_filter,#numeric_filter,#numeric_filter,#numeric_filter,#numeric_filter,#numeric_filter,#numeric_filter,#numeric_filter,#numeric_filter,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter")
    grid.setInitWidths("100,100,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75");
    grid.setSkin("dhx_skyblue")
    grid.init();
    grid.load("<%= data_departments_path%>");
  
</script>
    <input type="button" value="Excel" onclick='grid.toExcel("http://dhtmlxgrid.appspot.com/export/excel");'/>
    <input type="button" value="PDF" onclick='grid.toPDF("http://dhtmlxgrid.appspot.com/export/pdf");'/>
</html>