config/routes.rb
RiskAssessDemo::Application.routes.draw do
  root :to => "home#index"

  resources :departments do
    collection do
        get "data"
        get "view"
        get "dbaction"
      end
    resources :tasks do
      resources :hazards 
    end
  end

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js">
	</script>
<head>
  <title>RiskAssessDemo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<div class="header">
	<header>
		<div id="user_nav">
			<% if current_user %>
			  Logged in as <%= current_user.email %>
			 <% else %>
			   <%= link_to "Sign up", sign_up_path %>
			   <%= link_to "Log in", log_in_path %>
			 <% end %>
		</div>
		<% flash.each do |name, msg| %>
		  <%= content_tag :div, msg, :id => "flash_#{name}" %>
		<% end %>		
		<h1>Risk Assessment Application</h1>
		<h3>Version: 2.0</h3>
		<ul class="menu w90">
			<li><%= link_to 'Home', root_path, :class=>"link4" %></li>
			<li><%= link_to 'Departments', departments_path, :class=>"link4" %></li>
			<li><%= link_to 'Report', view_departments_path, :class=>"link4" %></li>
			<li><%= link_to "Log out", log_out_path, :class=>"link4" %></li>
		</ul>
	</header>
</div>

<body>

<%= yield %>

</body>
</html>